# Generated by Django 3.1.5 on 2021-01-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='SIV_name',
        ),
        migrations.AddField(
            model_name='site',
            name='SIV_Date',
            field=models.DateField(null=True),
        ),
    ]
