# Generated by Django 3.1.5 on 2021-01-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0002_auto_20210105_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='AV',
            field=models.CharField(max_length=400, verbose_name='Audio-Video Consent Taken'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='ECG',
            field=models.TimeField(verbose_name='ECG Time'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='avtime',
            field=models.TimeField(verbose_name='Audio-Video Conset Time'),
        ),
    ]
