# Generated by Django 3.1.5 on 2021-01-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0003_auto_20210105_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='ECG_Taken',
            field=models.CharField(max_length=200, null=True, verbose_name='ECG Taken'),
        ),
    ]
