# Generated by Django 3.1.5 on 2021-01-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0004_screening_ecg_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='ECG_Taken',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='ECG Taken'),
        ),
    ]
