# Generated by Django 3.1.5 on 2021-01-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0005_auto_20210105_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='AV',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=400, null=True, verbose_name='Audio-Video Consent Taken'),
        ),
    ]
