# Generated by Django 3.1.5 on 2021-01-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0006_auto_20210105_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='PD_Upload',
            field=models.FileField(null=True, upload_to='', verbose_name='Protocol Deviation Upload'),
        ),
        migrations.AddField(
            model_name='screening',
            name='Protocol_Deviation',
            field=models.CharField(max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='ECG',
            field=models.TimeField(help_text='If <b>Yes</b> please enter time.', verbose_name='ECG Time'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='PD',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Protocol deviation if any'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='avtime',
            field=models.TimeField(help_text='If <b>Yes</b> please enter time.', verbose_name='Audio-Video Conset Time'),
        ),
    ]
