# Generated by Django 3.1.5 on 2021-01-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0007_auto_20210105_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='day1',
            name='Protocol_Deviation',
            field=models.CharField(help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='DDT',
            field=models.TimeField(verbose_name='Drug Dosing Time'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='PD',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Protocol deviation if any'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='PK',
            field=models.TimeField(verbose_name='PK Blood Sample Time'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='Randomization',
            field=models.CharField(max_length=200, verbose_name='Randomization Number'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='patient_Withdrawal',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='day1',
            name='vital',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Vitals Taken'),
        ),
        migrations.AlterField(
            model_name='day2',
            name='DSAQ',
            field=models.CharField(max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day2',
            name='PEC',
            field=models.CharField(max_length=500, verbose_name='Physical Exam Done'),
        ),
        migrations.AlterField(
            model_name='day2',
            name='Vital',
            field=models.CharField(max_length=100, verbose_name='vitals'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='DSAQ',
            field=models.CharField(max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='PW',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='Vital',
            field=models.CharField(max_length=100, verbose_name='Vitals'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='other',
            field=models.TextField(blank=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='DSAQ',
            field=models.CharField(max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='PW',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='Vital',
            field=models.CharField(max_length=100, verbose_name='Vitals'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='DSAQ',
            field=models.CharField(max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='PW',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='Vital',
            field=models.CharField(max_length=100, verbose_name='Vitals'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='DSAQ',
            field=models.CharField(max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='PW',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='Vital',
            field=models.CharField(max_length=100, verbose_name='Vitals'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='DSAQ',
            field=models.CharField(max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='PW',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='Vital',
            field=models.CharField(max_length=100, verbose_name='Vitals'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='DSAQ',
            field=models.CharField(max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='PW',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='Vital',
            field=models.CharField(max_length=100, verbose_name='Vitals'),
        ),
        migrations.AlterField(
            model_name='lfu',
            name='DSAQ',
            field=models.CharField(max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='lfu',
            name='Vital',
            field=models.CharField(max_length=100, verbose_name='Vitals'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='Date',
            field=models.DateField(verbose_name='Screening Date'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='PD_Upload',
            field=models.FileField(help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='Protocol_Deviation',
            field=models.CharField(help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='avtime',
            field=models.TimeField(help_text='If <b>Yes</b> please enter time.', verbose_name='Audio-Video Consent Time'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='icpd',
            field=models.DateField(verbose_name='Informed Consent Process Date'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='vital',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Vitals Taken'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='DSAQ',
            field=models.CharField(max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='PW',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='Vital',
            field=models.CharField(max_length=100, verbose_name='Vitals'),
        ),
    ]
