# Generated by Django 3.1.5 on 2021-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0009_day1_pd_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day1',
            name='DDT',
            field=models.CharField(max_length=100, verbose_name='Drug Dosing Time'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='PK',
            field=models.CharField(max_length=100, verbose_name='PK Blood Sample Time'),
        ),
    ]
