# Generated by Django 3.1.5 on 2021-01-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0010_auto_20210105_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='day2',
            name='Protocol_Deviation',
            field=models.CharField(help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='PD_Upload',
            field=models.FileField(help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AlterField(
            model_name='day2',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='day2',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day2',
            name='PEC',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=500, verbose_name='Physical Exam Done'),
        ),
        migrations.AlterField(
            model_name='day2',
            name='Vital',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='vitals'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='PD_Upload',
            field=models.FileField(help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
    ]
