# Generated by Django 3.1.5 on 2021-01-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0011_auto_20210105_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='day1',
            name='other',
            field=models.TextField(blank=True, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='day2',
            name='other',
            field=models.TextField(blank=True, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='lfu',
            name='PW',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AddField(
            model_name='lfu',
            name='other',
            field=models.TextField(blank=True, verbose_name='Other Note'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='patient_Withdrawal',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day2',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='day2',
            name='Blood_Sample',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='day2',
            name='patient_Withdrawal',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day3',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='day3',
            name='DDT',
            field=models.CharField(max_length=10, verbose_name='Drugs Dosing Time'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='PEC',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=500, verbose_name='Physical Exam Done'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='PW',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='Vital',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='vitals'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='Blood_Sample',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='day4',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='day4',
            name='DDT',
            field=models.CharField(max_length=100, verbose_name='Drug Dosing Time'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='PEC',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=500, verbose_name='Physical Exam Done'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='PK',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='PK Blood Sample'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='PW',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='Vital',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='vitals'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='Blood_Sample',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='day5',
            name='DDT',
            field=models.CharField(max_length=100, verbose_name='Drug Dosing Time'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='PEC',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=500, verbose_name='Physical Exam Done'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='PK',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, verbose_name='PK Blood Sample'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='PW',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='Urine',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Urine Sample'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='Vital',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='vitals'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='Blood_Sample',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=500),
        ),
        migrations.AlterField(
            model_name='day6',
            name='DDT',
            field=models.CharField(max_length=100, verbose_name='Drug Dosing Time'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='PW',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='Vital',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='vitals'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='DDT',
            field=models.CharField(max_length=100, verbose_name='Drug Dosing Time'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='PW',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='DDT',
            field=models.CharField(max_length=100, verbose_name='Drug Dosing Time'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='PW',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='lfu',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='lfu',
            name='DDT',
            field=models.CharField(max_length=100, verbose_name='Drug Dosing Time'),
        ),
        migrations.AlterField(
            model_name='lfu',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='AER',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Adverse Event Record'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='DDT',
            field=models.CharField(max_length=100, verbose_name='Drug Dosing Time'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='DSAQ',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Daily Symptom Assessment Questionnaire Filled'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='PW',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
    ]
