# Generated by Django 3.1.5 on 2021-01-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0012_auto_20210105_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day1',
            name='patient_initials',
        ),
        migrations.RemoveField(
            model_name='day3',
            name='PD',
        ),
        migrations.RemoveField(
            model_name='day4',
            name='PD',
        ),
        migrations.RemoveField(
            model_name='day5',
            name='PD',
        ),
        migrations.RemoveField(
            model_name='day6',
            name='PD',
        ),
        migrations.RemoveField(
            model_name='eoiv',
            name='PD',
        ),
        migrations.RemoveField(
            model_name='eot',
            name='PD',
        ),
        migrations.RemoveField(
            model_name='lfu',
            name='PD',
        ),
        migrations.RemoveField(
            model_name='toc',
            name='PD',
        ),
        migrations.AddField(
            model_name='day2',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AddField(
            model_name='day3',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AddField(
            model_name='day3',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AddField(
            model_name='day3',
            name='patient_Withdrawal',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='day4',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AddField(
            model_name='day4',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AddField(
            model_name='day5',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AddField(
            model_name='day5',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AddField(
            model_name='day6',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AddField(
            model_name='day6',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AddField(
            model_name='eoiv',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AddField(
            model_name='eoiv',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AddField(
            model_name='eot',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AddField(
            model_name='eot',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AddField(
            model_name='lfu',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AddField(
            model_name='lfu',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AddField(
            model_name='toc',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AddField(
            model_name='toc',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AlterField(
            model_name='day2',
            name='PD',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=500, verbose_name='Protocol deviation if any'),
        ),
        migrations.AlterField(
            model_name='day2',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='PD_Upload',
            field=models.FileField(blank=True, help_text='If <b>Yes</b> Upload file', null=True, upload_to='', verbose_name='Protocol Deviation Upload File'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='Protocol_Deviation',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
    ]
