# Generated by Django 3.1.5 on 2021-01-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0013_auto_20210105_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='day1',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='day1',
            name='PK_Blood',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='PK Blood Sample Taken'),
        ),
        migrations.AddField(
            model_name='day1',
            name='PK_second',
            field=models.CharField(max_length=100, null=True, verbose_name='Second Sample Time'),
        ),
        migrations.AddField(
            model_name='day2',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='day3',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='day3',
            name='PK_Blood',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True, verbose_name='PK Blood Sample Taken'),
        ),
        migrations.AddField(
            model_name='day3',
            name='PK_Fourth',
            field=models.CharField(max_length=100, null=True, verbose_name='Fourth Sample Time'),
        ),
        migrations.AddField(
            model_name='day3',
            name='PK_Third',
            field=models.CharField(max_length=100, null=True, verbose_name='Third Sample Time'),
        ),
        migrations.AddField(
            model_name='day3',
            name='PK_second',
            field=models.CharField(max_length=100, null=True, verbose_name='Second Sample Time'),
        ),
        migrations.AddField(
            model_name='day4',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='day5',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='day6',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='eoiv',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='eot',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='lfu',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='screening',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AddField(
            model_name='toc',
            name='AE',
            field=models.CharField(blank=True, help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Adverse Event Record Description'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='PK',
            field=models.CharField(max_length=100, null=True, verbose_name='First Sample Time'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='day3',
            name='PK',
            field=models.CharField(max_length=100, null=True, verbose_name='First Sample Time'),
        ),
    ]
