# Generated by Django 3.1.5 on 2021-01-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0014_auto_20210105_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day1',
            name='DOB',
            field=models.CharField(max_length=100, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='day1',
            name='patient_Withdrawal',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day2',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='day4',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100, verbose_name='Blood Sample Time'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100, verbose_name='Blood Sample Time'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100, verbose_name='Blood Sample Time'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100, verbose_name='Blood Sample Time'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='lfu',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100, verbose_name='Blood Sample Time'),
        ),
        migrations.AlterField(
            model_name='lfu',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='lfu',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='BST',
            field=models.CharField(max_length=100, verbose_name='Blood Sample Time'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='DOB',
            field=models.DateField(max_length=100, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Screening Date'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='ECG',
            field=models.CharField(help_text='If <b>Yes</b> please enter time.', max_length=100, verbose_name='ECG Time'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='avtime',
            field=models.CharField(help_text='If <b>Yes</b> please enter time.', max_length=100, verbose_name='Audio-Video Consent Time'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='icpd',
            field=models.CharField(max_length=100, verbose_name='Informed Consent Process Date'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='ust',
            field=models.CharField(max_length=100, verbose_name='Urine Sample Time'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='Blood_Sample_Time',
            field=models.CharField(max_length=100, verbose_name='Blood Sample Time'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
    ]
