# Generated by Django 3.1.5 on 2021-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0016_auto_20210111_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day1',
            name='patient_Withdrawal',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day2',
            name='patient_Withdrawal',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day3',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day3',
            name='patient_Withdrawal',
            field=models.CharField(choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='day4',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day5',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='day6',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='eoiv',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='eot',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='lfu',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='PW',
            field=models.CharField(blank=True, choices=[('W', 'Withdrawal of consent'), ('S', 'Significant subject noncompliance'), ('n', 'Investigator Decision'), ('o', 'Other'), ('n', 'No')], max_length=100, null=True, verbose_name='Patient Withdrawal'),
        ),
    ]
