# Generated by Django 3.1.5 on 2021-01-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0017_auto_20210111_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='Protocol_Deviation',
            field=models.CharField(help_text='If <b>Yes</b> Enter Description', max_length=500, null=True, verbose_name='Protocol deviation Description'),
        ),
    ]
