# Generated by Django 3.1.5 on 2021-01-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0019_auto_20210112_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('The', models.CharField(max_length=200)),
                ('PI', models.FilePathField(max_length=200)),
                ('sub_I', models.FilePathField(max_length=200)),
            ],
            options={
                'verbose_name': 'Site Registration',
                'verbose_name_plural': 'Site Registration',
            },
        ),
        migrations.AlterModelOptions(
            name='day1',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Day 1'},
        ),
        migrations.AlterModelOptions(
            name='day2',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Day 2'},
        ),
        migrations.AlterModelOptions(
            name='day3',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Day 3'},
        ),
        migrations.AlterModelOptions(
            name='day4',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Day 4'},
        ),
        migrations.AlterModelOptions(
            name='day5',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Day 5'},
        ),
        migrations.AlterModelOptions(
            name='day6',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Day 6'},
        ),
        migrations.AlterModelOptions(
            name='eoiv',
            options={'verbose_name': 'EOVI', 'verbose_name_plural': 'EOVI'},
        ),
        migrations.AlterModelOptions(
            name='eot',
            options={'verbose_name': 'EOT', 'verbose_name_plural': 'EOT'},
        ),
        migrations.AlterModelOptions(
            name='lfu',
            options={'verbose_name': 'LFU', 'verbose_name_plural': 'LFU'},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'verbose_name': 'Protocol', 'verbose_name_plural': 'Protocol'},
        ),
        migrations.AlterModelOptions(
            name='screening',
            options={'verbose_name': 'Screening', 'verbose_name_plural': 'Screening'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Site'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsor'},
        ),
        migrations.AlterModelOptions(
            name='toc',
            options={'verbose_name': 'TOC', 'verbose_name_plural': 'TOC'},
        ),
    ]
