# Generated by Django 3.1.5 on 2021-01-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0020_auto_20210122_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TH', models.CharField(max_length=200, verbose_name='Therapetic Areas')),
                ('PI', models.FileField(upload_to='', verbose_name='PI Data upload')),
                ('sub', models.CharField(max_length=100, verbose_name='sub-I data')),
            ],
        ),
    ]
