# Generated by Django 3.1.5 on 2021-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0021_siteregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PI', models.FileField(upload_to='', verbose_name='EC Data Upload')),
            ],
        ),
        migrations.DeleteModel(
            name='siteRegistration',
        ),
    ]
