# Generated by Django 3.1.5 on 2021-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0022_auto_20210129_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='labdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.FileField(upload_to='', verbose_name='Lab Data upload')),
            ],
        ),
    ]
