# Generated by Django 3.1.5 on 2021-01-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsl', '0023_labdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ECdata',
        ),
        migrations.DeleteModel(
            name='labdata',
        ),
        migrations.AddField(
            model_name='site_registration',
            name='ECdata',
            field=models.FileField(blank=True, upload_to='', verbose_name='EC Data Upload'),
        ),
        migrations.AddField(
            model_name='site_registration',
            name='lab',
            field=models.FileField(blank=True, upload_to='', verbose_name='Lab Data upload'),
        ),
        migrations.AlterField(
            model_name='site_registration',
            name='PI',
            field=models.FileField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='site_registration',
            name='sub_I',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
